// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketHive.Server.Data;

#nullable disable

namespace TicketHive.Server.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230404061938_InitialMainDb")]
    partial class InitialMainDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventModelUserModel", b =>
                {
                    b.Property<int>("BookingsId")
                        .HasColumnType("int");

                    b.Property<int>("VisitorsId")
                        .HasColumnType("int");

                    b.HasKey("BookingsId", "VisitorsId");

                    b.HasIndex("VisitorsId");

                    b.ToTable("EventModelUserModel");
                });

            modelBuilder.Entity("TicketHive.Shared.Models.EventModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfTickets")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A concert featuring various artists in the local park",
                            EventType = 0,
                            Host = "The local community council",
                            ImageUrl = "~/images/event images/image 1.avif",
                            Name = "Concert in the park",
                            NumberOfTickets = 1000,
                            Price = 350m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A new exhibit featuring local artists",
                            EventType = 1,
                            Host = "The local art museum",
                            ImageUrl = "~/images/event images/image 2.avif",
                            Name = "Art exhibit opening",
                            NumberOfTickets = 500,
                            Price = 100m
                        },
                        new
                        {
                            Id = 3,
                            Description = "A wine tasting featuring local wineries",
                            EventType = 2,
                            Host = "The Wine Association",
                            ImageUrl = "~/images/event images/image 3.avif",
                            Name = "Wine tasting",
                            NumberOfTickets = 300,
                            Price = 200m
                        },
                        new
                        {
                            Id = 4,
                            Description = "A charity run to raise funds for local causes",
                            EventType = 3,
                            Host = "The local sports association",
                            ImageUrl = "~/images/event images/image 4.avif",
                            Name = "Charity run",
                            NumberOfTickets = 2000,
                            Price = 800m
                        },
                        new
                        {
                            Id = 5,
                            Description = "A comedy show featuring local comedians",
                            EventType = 4,
                            Host = "The Comedy Club",
                            ImageUrl = "~/images/event images/image 5.avif",
                            Name = "Comedy show",
                            NumberOfTickets = 500,
                            Price = 100m
                        },
                        new
                        {
                            Id = 6,
                            Description = "A film festival showcasing international films",
                            EventType = 5,
                            Host = "The Film Society",
                            ImageUrl = "~/images/event images/image 6.avif",
                            Name = "Film festival",
                            NumberOfTickets = 120,
                            Price = 300m
                        },
                        new
                        {
                            Id = 7,
                            Description = "A music festival featuring international musicians",
                            EventType = 6,
                            Host = "Music Association",
                            ImageUrl = "~/images/event images/image 7.avif",
                            Name = "Local music festival",
                            NumberOfTickets = 5000,
                            Price = 1500m
                        },
                        new
                        {
                            Id = 8,
                            Description = "A fair featuring local artisans selling their crafts",
                            EventType = 7,
                            Host = "Local artisans association",
                            ImageUrl = "~/images/event images/image 8.avif",
                            Name = "Artisan fair",
                            NumberOfTickets = 1000,
                            Price = 50m
                        },
                        new
                        {
                            Id = 9,
                            Description = "A one day class on theater production of a classic play",
                            EventType = 10,
                            Host = "Educate Theater Association",
                            ImageUrl = "~/images/event images/image 9.avif",
                            Name = "Theater production",
                            NumberOfTickets = 100,
                            Price = 1200m
                        },
                        new
                        {
                            Id = 10,
                            Description = "A day of family fun featuring various activities for kids and adults",
                            EventType = 8,
                            Host = "The local community center",
                            ImageUrl = "~/images/event images/image 10.avif",
                            Name = "Family fun day",
                            NumberOfTickets = 350,
                            Price = 80m
                        },
                        new
                        {
                            Id = 11,
                            Description = "A science fair featuring local scientists and their research",
                            EventType = 9,
                            Host = "The local science museum",
                            ImageUrl = "~/images/event images/image 11.avif",
                            Name = "Science fair",
                            NumberOfTickets = 1000,
                            Price = 50m
                        },
                        new
                        {
                            Id = 12,
                            Description = "A fashion show featuring various international designers",
                            EventType = 4,
                            Host = "The Fashion association",
                            ImageUrl = "~/images/event images/image 12.avif",
                            Name = "Fashion show",
                            NumberOfTickets = 300,
                            Price = 450m
                        },
                        new
                        {
                            Id = 13,
                            Description = "A formal gala dinner featuring gourmet cuisine and live entertainment",
                            EventType = 2,
                            Host = "Food&Wine Inc",
                            ImageUrl = "~/images/event images/image 13.avif",
                            Name = "Gala dinner",
                            NumberOfTickets = 300,
                            Price = 1500m
                        },
                        new
                        {
                            Id = 14,
                            Description = "A lecture series featuring renowned speakers on various topics",
                            EventType = 1,
                            Host = "The local university",
                            ImageUrl = "~/images/event images/image 14.avif",
                            Name = "Lecture series",
                            NumberOfTickets = 500,
                            Price = 90m
                        },
                        new
                        {
                            Id = 15,
                            Description = "A tech meetup featuring local tech entrepreneurs and their startups",
                            EventType = 11,
                            Host = "Local startup incubator",
                            ImageUrl = "~/images/event images/image 15.avif",
                            Name = "Tech meetup",
                            NumberOfTickets = 50,
                            Price = 900m
                        },
                        new
                        {
                            Id = 16,
                            Description = "A trivia night featuring various categories and fine prizes",
                            EventType = 12,
                            Host = "The local pub",
                            ImageUrl = "~/images/event images/image 16.avif",
                            Name = "Trivia night",
                            NumberOfTickets = 70,
                            Price = 150m
                        },
                        new
                        {
                            Id = 17,
                            Description = "A party featuring international DJ:s and live entertainment",
                            EventType = 13,
                            Host = "The local nightclub",
                            ImageUrl = "~/images/event images/image 17.avif",
                            Name = "DJ party",
                            NumberOfTickets = 400,
                            Price = 250m
                        },
                        new
                        {
                            Id = 18,
                            Description = "An art workshop featuring a local artist teaching a new technique",
                            EventType = 14,
                            Host = "The local art school",
                            ImageUrl = "~/images/event images/image 18.avif",
                            Name = "Art workshop",
                            NumberOfTickets = 50,
                            Price = 100m
                        },
                        new
                        {
                            Id = 19,
                            Description = "A screening of a new surprise movie with Q&A session with the director",
                            EventType = 5,
                            Host = "The local movie theatre",
                            ImageUrl = "~/images/event images/image 19.avif",
                            Name = "Movie screening",
                            NumberOfTickets = 70,
                            Price = 200m
                        },
                        new
                        {
                            Id = 20,
                            Description = "A charity walk to raise funds for a local charity",
                            EventType = 3,
                            Host = "Local community organizatio",
                            ImageUrl = "~/images/event images/image 20.avif",
                            Name = "Charity walk",
                            NumberOfTickets = 1500,
                            Price = 0m
                        },
                        new
                        {
                            Id = 21,
                            Description = "A night of stand-up comedy featuring local comedians",
                            EventType = 4,
                            Host = "The local comedy club",
                            ImageUrl = "~/images/event images/image 21.avif",
                            Name = "Comedy night",
                            NumberOfTickets = 200,
                            Price = 250m
                        },
                        new
                        {
                            Id = 22,
                            Description = "A wine tasting event featuring local wineries",
                            EventType = 2,
                            Host = "The local wine association",
                            ImageUrl = "~/images/event images/image 22.avif",
                            Name = "Wine tasting",
                            NumberOfTickets = 100,
                            Price = 300m
                        },
                        new
                        {
                            Id = 23,
                            Description = "A fitness class featuring a local instructor",
                            EventType = 15,
                            Host = "The local gym",
                            ImageUrl = "~/images/event images/image 23.avif",
                            Name = "Fitness class",
                            NumberOfTickets = 80,
                            Price = 100m
                        },
                        new
                        {
                            Id = 24,
                            Description = "A tech workshop were you get to build your own miniature robot",
                            EventType = 14,
                            Host = "International Robot Inc",
                            ImageUrl = "~/images/event images/image 24.avif",
                            Name = "Build your own robot",
                            NumberOfTickets = 1000,
                            Price = 1500m
                        },
                        new
                        {
                            Id = 25,
                            Description = "An unplugged concert featuring various artists in the local park",
                            EventType = 0,
                            Host = "The local community council",
                            ImageUrl = "~/images/event images/image 25.avif",
                            Name = "Unplugged concert",
                            NumberOfTickets = 1000,
                            Price = 350m
                        },
                        new
                        {
                            Id = 26,
                            Description = "A new exhibit featuring local artists",
                            EventType = 1,
                            Host = "The local art museum",
                            ImageUrl = "~/images/event images/image 26.avif",
                            Name = "Art exhibit opening",
                            NumberOfTickets = 500,
                            Price = 100m
                        });
                });

            modelBuilder.Entity("TicketHive.Shared.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventModelUserModel", b =>
                {
                    b.HasOne("TicketHive.Shared.Models.EventModel", null)
                        .WithMany()
                        .HasForeignKey("BookingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketHive.Shared.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("VisitorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
